'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{startServer}=require('../src/server.cjs'),{parseCube}=require('../src/cube.cjs'),nav=require('../ui/look-navigation.js'),adapter=require('../src/look-adapter.cjs');
const identity=Buffer.from('LUT_3D_SIZE 2\n'+[0,1].flatMap(b=>[0,1].flatMap(g=>[0,1].map(r=>`${r} ${g} ${b}`))).join('\n'));
async function session(ai){const root=fs.mkdtempSync(path.join(os.tmpdir(),'lut-porting-test-')),app=await startServer({root,port:0,ai}),r=await fetch(app.url),h=await r.text(),boot=JSON.parse(h.match(/id="product-boot"[^>]*>([\s\S]*?)<\/script>/)[1]),headers={Cookie:r.headers.get('set-cookie').split(';')[0],'X-LUT-Token':boot.token,'Content-Type':'application/json'},p=boot.projectId;const request=async(method,payload={})=>{const r=await fetch(app.url+'/api/call',{method:'POST',headers,body:JSON.stringify({method,payload:{projectId:p,...payload}})});return {status:r.status,...await r.json()};},call=async(...args)=>{const x=await request(...args);assert.equal(x.status,200,x.error);return x.data;};return {root,app,p,call,request,close:async()=>{await app.close();fs.rmSync(root,{recursive:true,force:true});}};}
test('Default project name, conflict-safe rename, persistent Undo/Redo and independent project names',async()=>{
 const t=await session();try{let state=await t.call('state');assert.equal(state.projects[0].name,'My Project');const second=await t.call('project',{name:'Second'}),other=second.projects.at(-1).id;
 state=await t.call('renameProject',{name:' My camera tests ',expectedName:'My Project'});assert.equal(state.projects[0].name,'My camera tests');assert.equal(state.projects.at(-1).name,'Second');
 assert.equal((await t.request('renameProject',{name:'Stale',expectedName:'My Project'})).status,400);assert.equal((await t.request('renameProject',{name:'   ',expectedName:'My camera tests'})).status,400);
 assert.equal((await t.call('undo',{projectId:other})).projects[0].name,'My camera tests');assert.equal((await t.call('undo')).projects[0].name,'My Project');assert.equal((await t.call('redo')).projects[0].name,'My camera tests');
 assert.equal(t.app.store.one('SELECT name FROM projects WHERE id=?',[t.p]).name,'My camera tests');
 }finally{await t.close();}
});
test('Bidirectional porting preserves family and original bytes, reuses existing variants and rejects unknown/RAW/unsupported inputs',async()=>{
 const t=await session();try{const s=t.app.store,sha=parseCube(identity).sha256;fs.writeFileSync(path.join(t.root,'luts/apple.cube'),identity);s.change(()=>s.db.run('INSERT INTO luts(id,name,original_name,sha256,asset,size,input,output,details) VALUES (?,?,?,?,?,?,?,?,?)',['apple','Original Apple','original.cube',sha,'luts/apple.cube',2,'apple-log2','rec709',JSON.stringify({code:'APL'})]));
 const result=await t.call('adaptLut',{id:'apple',targetProfile:'sony-slog3-sgamut3cine',targetDevice:'Sony A7 IV'}),row=(await t.call('state')).luts.find(l=>l.id===result.id);assert.equal(row.size,33);assert.equal(row.input,'sony-slog3-sgamut3cine');assert.equal(nav.family(row),sha);assert.deepEqual(fs.readFileSync(path.join(t.root,'luts/apple.cube')),identity);
 assert.equal((await t.call('adaptLut',{id:result.id,targetProfile:'apple-log2'})).id,'apple');assert.equal((await t.call('adaptLut',{id:'apple',targetProfile:'sony-slog3-sgamut3cine'})).duplicate,true);assert.equal((await t.call('state')).luts.length,2);
 const other=(await t.call('project',{name:'Other'})).projects.at(-1).id;s.change(()=>s.db.run('INSERT INTO ui_state VALUES (?,?,?)',[other,'first',JSON.stringify({favourites:['apple.cube'],theme:'light',adjustments:{}})]));await t.call('adaptLut',{projectId:other,id:'apple',targetProfile:'sony-slog3-sgamut3cine'});const prefs=JSON.parse(s.one('SELECT state FROM ui_state WHERE project_id=?',[other]).state);assert.ok(prefs.favourites.includes(result.id+'.cube'));assert.equal(prefs.theme,'light');
 for(const targetProfile of ['unknown','prores-raw','hlg-bt2020','apple-log2'])assert.equal((await t.request('adaptLut',{id:'apple',targetProfile})).status,400);
 for(const v of [-.05,0,.01,.18,1,10])assert.ok(Math.abs(adapter.appleDecode(adapter.appleEncode(v))-v)<2e-7);
 const baked=adapter.sampler(fs.readFileSync(path.join(t.root,row.asset)));for(const rgb of [[.25,.5,.75],[.5,.5,.5]]){const expected=adapter.transform(rgb,'apple-log2','sony-slog3-sgamut3cine').map(v=>Math.max(0,Math.min(1,v)));baked(rgb).forEach((v,i)=>assert.ok(Math.abs(v-expected[i])<1e-8));}
 }finally{await t.close();}
});
test('AI port review has actual matching previews, preserves family code/creator and never writes without review',async()=>{
 let observed;const t=await session({status:async()=>[{id:'codex',ready:true}],suggest:async value=>{observed=value;return {name:'Suggested port',code:'NEW',maker:'Invented',description:'A warm look.',tags:'warm'};}});
 try{const s=t.app.store,sha=parseCube(identity).sha256;fs.writeFileSync(path.join(t.root,'luts/source.cube'),identity);s.change(()=>{s.db.run('INSERT INTO luts(id,name,original_name,sha256,asset,size,input,output,details) VALUES (?,?,?,?,?,?,?,?,?)',['source','Source','source.cube',sha,'luts/source.cube',2,'sony-slog3-sgamut3cine','rec709',JSON.stringify({code:'SRC',maker:'Creator'})]);s.db.run('INSERT INTO clips VALUES (?,?,?,?,?,?)',['clip',t.p,'iphone.mov','unused','apple-log2','{}']);s.db.run('INSERT INTO scenes(id,project_id,clip_id,name,frame_index,pts,time_base,asset,thumb,sha256,details) VALUES (?,?,?,?,?,?,?,?,?,?,?)',['scene',t.p,'clip','Phone',0,'0','1/24','frames/a.png','frames/a.jpg','frame-hash','{}']);});fs.writeFileSync(path.join(t.root,'frames/a.jpg'),'original-preview-fixture');
 const port=await t.call('adaptLut',{id:'source'}),row=(await t.call('state')).luts.find(l=>l.id===port.id);fs.writeFileSync(path.join(t.root,'cache',`frame-hash-${row.sha256}-preview-v2.jpg`),'actual-render-path-fixture');const before=fs.readFileSync(s.file),suggested=await t.call('aiSuggest',{kind:'lut',id:port.id,provider:'codex',sceneId:'scene'});assert.equal(observed.images.length,2);assert.ok(observed.images.every(f=>fs.existsSync(f)));assert.match(observed.prompt,/colour math is already fixed/);assert.equal(suggested.suggestion.code,'SRC');assert.equal(suggested.suggestion.maker,'Creator');assert.deepEqual(fs.readFileSync(s.file),before);
 await t.call('updateBatch',{kind:'lut',items:[{id:port.id,expectedRevision:suggested.baseRevision,fields:{name:suggested.suggestion.name,description:suggested.suggestion.description},aiSource:suggested.source}]});const saved=(await t.call('state')).luts.find(l=>l.id===port.id);assert.equal(saved.name,'Suggested port');assert.equal(nav.family(saved),sha);assert.equal(saved.input,'apple-log2');assert.equal(JSON.parse(saved.details).code,'SRC');
 }finally{await t.close();}
});
test('All published camera profiles port through the HTTP workflow with finite 33-point copies and stable families',async()=>{
 const t=await session();try{const s=t.app.store,profiles=await t.call('portProfiles');assert.equal(profiles.length,16);
 for(const p of profiles){const id=p.id,bytes=Buffer.concat([Buffer.from('TITLE "'+id+'"\n'),identity]),sha=parseCube(bytes).sha256;fs.writeFileSync(path.join(t.root,'luts',id+'.cube'),bytes);s.change(()=>s.db.run('INSERT INTO luts(id,name,original_name,sha256,asset,size,input,output,details) VALUES (?,?,?,?,?,?,?,?,?)',[id,p.label,id+'.cube',sha,'luts/'+id+'.cube',2,id,'rec709',JSON.stringify({code:'P'+profiles.indexOf(p).toString(36).toUpperCase().padStart(2,'0')})]));
  const targetProfile=id==='apple-log2'?'sony-slog3-sgamut3cine':'apple-log2',result=await t.call('adaptLut',{id,targetProfile,targetDevice:'Test device'}),row=s.one('SELECT * FROM luts WHERE id=?',[result.id]),bytesOut=fs.readFileSync(path.join(t.root,row.asset));assert.equal(parseCube(bytesOut).size,33);assert.equal(row.input,targetProfile);assert.equal(nav.family(row),sha);const sample=adapter.sampler(bytesOut);for(const rgb of [[0,0,0],[.25,.5,.75],[1,1,1]]){const expected=adapter.transform(rgb,id,targetProfile).map(v=>Math.max(0,Math.min(1,v)));sample(rgb).forEach((v,i)=>assert.ok(Math.abs(v-expected[i])<1e-8,id));}
  assert.equal((await t.call('adaptLut',{id:row.id,targetProfile:id})).id,id,'Returning to original profile reuses the original instead of baking twice');
 }
 }finally{await t.close();}
});
