'use strict';
const fs=require('node:fs'),fsp=require('node:fs/promises'),path=require('node:path'),{randomUUID,createHash}=require('node:crypto'),{pipeline}=require('node:stream/promises'),yazl=require('yazl'),yauzl=require('yauzl');
const {parseCube,profile}=require('./cube.cjs'),media=require('./media.cjs'),{canShareCode}=require('../ui/look-navigation.js');
const rows=(db,sql,args=[])=>{const s=db.prepare(sql);try{s.bind(args);const r=[];while(s.step())r.push(s.getAsObject());return r;}finally{s.free();}};
const safe=name=>typeof name==='string'&&/^(frames|clips|gallery|luts)\/[\w./-]+$/.test(name)&&!name.split('/').some(p=>p==='..'||p==='.'||!p);
function sourceFile(root,name){if(!safe(name))throw Error('Invalid project asset path.');const file=path.join(root,name);if(!fs.realpathSync(file).startsWith(fs.realpathSync(root)+path.sep))throw Error('Project asset is outside its library.');return file;}
async function manifest(store,projectId,signal){
 const query=(sql,args)=>rows(store.db,sql,args),project=query('SELECT * FROM projects WHERE id=?',[projectId])[0];if(!project)throw Error('Choose an existing project.');
 const data={format:'lut-explorer-project',version:1,project,clips:query('SELECT * FROM clips WHERE project_id=?',[projectId]),scenes:query('SELECT * FROM scenes WHERE project_id=?',[projectId]),collections:query('SELECT * FROM collections WHERE project_id=?',[projectId]),memberships:query('SELECT m.* FROM memberships m JOIN scenes s ON s.id=m.scene_id WHERE s.project_id=?',[projectId]),scene_orders:query('SELECT * FROM scene_orders WHERE project_id=?',[projectId]),collection_orders:query('SELECT * FROM collection_orders WHERE project_id=?',[projectId]),luts:query('SELECT * FROM luts ORDER BY position IS NULL,position,rowid'),settings:query('SELECT * FROM ui_state WHERE project_id=?',[projectId])[0]||null,files:[]};
 const prefs=data.settings?JSON.parse(data.settings.state):{favourites:data.luts.filter(l=>l.favourite).map(l=>JSON.parse(l.details).legacy?l.original_name:`${l.id}.cube`),adjustments:{},theme:'dark'};if(prefs.lutOrder){const order=new Map(prefs.lutOrder.map((id,i)=>[id,i]));data.luts.sort((a,b)=>(order.get(a.id)??Infinity)-(order.get(b.id)??Infinity));}prefs.lutOrder=data.luts.map(l=>l.id);data.settings={project_id:projectId,revision:data.settings?.revision||randomUUID(),state:JSON.stringify(prefs)};
 const files=new Set();const add=name=>{if(safe(name)&&fs.existsSync(path.join(store.root,name)))files.add(name);};
 function references(value){if(typeof value==='string')add(value.replace(/^assets\//,''));else if(Array.isArray(value))value.forEach(references);else if(value&&typeof value==='object')Object.values(value).forEach(references);}
 for(const clip of data.clips){const m=JSON.parse(clip.metadata);if(m.librarySource)add(m.librarySource);clip.source='';if(m.format)delete m.format.filename;clip.metadata=JSON.stringify(m);}
 for(const s of data.scenes){add(s.asset);add(s.thumb);references(JSON.parse(s.details));if(JSON.parse(s.details).legacy)for(const l of data.luts){const d=JSON.parse(l.details);if(d.legacy)add(`gallery/${s.id}/${d.code}.jpg`);}}
 for(const l of data.luts)add(l.asset);
 for(const name of files){signal?.throwIfAborted();const file=sourceFile(store.root,name);data.files.push({name,size:fs.statSync(file).size,sha256:await media.digest(file,signal)});}
 for(const s of data.scenes)for(const name of [s.asset,s.thumb])if(!files.has(name))throw Error('A saved scene image is missing. Restore it before saving this project.');for(const l of data.luts)if(!files.has(l.asset))throw Error('A LUT file is missing. Restore it before saving this project.');
 return data;
}
async function save(store,projectId,destination,signal){const data=await manifest(store,projectId,signal),zip=new yazl.ZipFile();zip.addBuffer(Buffer.from(JSON.stringify(data)),'project.json');for(const f of data.files)zip.addFile(sourceFile(store.root,f.name),f.name,{compress:!f.name.startsWith('clips/')});const abort=()=>zip.outputStream.destroy(signal.reason);signal?.addEventListener('abort',abort,{once:true});const done=pipeline(zip.outputStream,fs.createWriteStream(destination,{flags:'wx',mode:0o600}),{signal});zip.end();try{await done;return data;}catch(e){await fsp.unlink(destination).catch(()=>{});throw e;}finally{signal?.removeEventListener('abort',abort);}}
async function extract(file,folder,signal){
 const zip=await new Promise((resolve,reject)=>yauzl.open(file,{lazyEntries:true,validateEntrySizes:true},(e,z)=>e?reject(e):resolve(z))),names=new Set();
 try{await new Promise((resolve,reject)=>{const abort=()=>{zip.close();reject(signal.reason);};signal?.addEventListener('abort',abort,{once:true});const finish=e=>{signal?.removeEventListener('abort',abort);e?reject(e):resolve();};zip.on('error',finish);zip.on('end',()=>finish());zip.on('entry',async entry=>{try{signal?.throwIfAborted();const name=entry.fileName,mode=entry.externalFileAttributes>>>16;if(name!=='project.json'&&!safe(name)||names.has(name)||((mode&0o170000)===0o120000)||entry.generalPurposeBitFlag&1)throw Error('This project contains an invalid or repeated file.');names.add(name);if(name==='project.json'&&entry.uncompressedSize>16*1024*1024)throw Error('Project manifest is too large.');const target=path.join(folder,name);await fsp.mkdir(path.dirname(target),{recursive:true});const input=await new Promise((r,j)=>zip.openReadStream(entry,(e,s)=>e?j(e):r(s)));await pipeline(input,fs.createWriteStream(target,{flags:'wx',mode:0o600}),{signal});zip.readEntry();}catch(e){zip.close();finish(e);}});zip.readEntry();});return names;}finally{zip.close();}
}
function validate(data){
 if(data?.format!=='lut-explorer-project'||data.version!==1||!data.project||typeof data.project.name!=='string'||!data.project.name.trim()||data.project.name.length>160)throw Error('Choose a supported LUT Buddy project file.');
 for(const table of ['clips','scenes','collections','memberships','scene_orders','collection_orders','luts','files'])if(!Array.isArray(data[table]))throw Error('Project records are incomplete.');
 const index=(table)=>{const map=new Map();for(const row of data[table]){if(typeof row.id!=='string'||map.has(row.id))throw Error('Project has repeated or invalid records.');map.set(row.id,row);}return map;};const clips=index('clips'),scenes=index('scenes'),groups=index('collections');index('luts');
 for(const c of clips.values()){if(c.project_id!==data.project.id)throw Error('Clip belongs to another project.');profile(c.profile);JSON.parse(c.metadata);}
 for(const s of scenes.values()){if(s.project_id!==data.project.id||!clips.has(s.clip_id)||!Number.isInteger(s.frame_index)||s.frame_index<0||typeof s.name!=='string'||!s.name.trim()||s.name.length>160||!/^\d+\/\d+$/.test(s.time_base)||!/^[-\d]+$/.test(s.pts))throw Error('A scene record is invalid.');JSON.parse(s.details);}
 for(const g of groups.values())if(g.project_id!==data.project.id||typeof g.name!=='string'||!g.name.trim()||g.name.length>160)throw Error('A collection is invalid.');
 for(const m of data.memberships)if(!scenes.has(m.scene_id)||!groups.has(m.collection_id))throw Error('A collection membership is invalid.');
 for(const o of data.scene_orders)if(o.project_id!==data.project.id||!scenes.has(o.scene_id)||(o.scope&&!groups.has(o.scope))||!Number.isInteger(o.position)||o.position<0)throw Error('Scene order is invalid.');
 for(const o of data.collection_orders)if(o.project_id!==data.project.id||!groups.has(o.collection_id)||!Number.isInteger(o.position)||o.position<0)throw Error('Collection order is invalid.');
 for(const l of data.luts){profile(l.input);profile(l.output);JSON.parse(l.details);if(!/^[a-f0-9]{64}$/.test(l.sha256))throw Error('LUT identity is invalid.');}
 if(data.settings){if(data.settings.project_id!==data.project.id)throw Error('Project settings are invalid.');const state=JSON.parse(data.settings.state);if(!state||typeof state!=='object'||!Array.isArray(state.favourites))throw Error('Project settings are invalid.');}
 const files=new Map();for(const f of data.files){if(!safe(f.name)||files.has(f.name)||!Number.isSafeInteger(f.size)||f.size<0||!/^[a-f0-9]{64}$/.test(f.sha256))throw Error('Project file list is invalid.');files.set(f.name,f);}
 for(const s of scenes.values())for(const name of [s.asset,s.thumb])if(!files.has(name))throw Error('A scene image is missing.');for(const l of data.luts)if(!files.has(l.asset))throw Error('A LUT is missing.');return files;
}
async function importData(store,data,sourceRoot,signal){
 const files=validate(data);for(const f of files.values()){signal?.throwIfAborted();const file=sourceFile(sourceRoot,f.name);if(fs.statSync(file).size!==f.size||await media.digest(file,signal)!==f.sha256)throw Error('A project file is incomplete or changed. Nothing was opened.');}
 for(const s of data.scenes)if(files.get(s.asset).sha256!==s.sha256)throw Error('A scene image does not match its saved identity.');
 for(const l of data.luts){const parsed=parseCube(fs.readFileSync(sourceFile(sourceRoot,l.asset)));if(parsed.sha256!==l.sha256||parsed.size!==l.size)throw Error('LUT contents do not match this project.');}
 const projectId=randomUUID(),maps={clips:new Map(),scenes:new Map(),collections:new Map(),luts:new Map()},assetMap=new Map(),created=[];
 for(const table of ['clips','scenes','collections'])for(const row of data[table])maps[table].set(row.id,randomUUID());
 const existing=store.query('SELECT * FROM luts'),usedCodes=new Set(existing.map(l=>{const d=JSON.parse(l.details);return d.displayCode||d.code;}));usedCodes.add('LOG');const newLuts=[];
 for(const l of data.luts){const old=existing.find(r=>r.sha256===l.sha256);if(old){maps.luts.set(l.id,old.id);assetMap.set(l.asset,old.asset);continue;}const id=randomUUID(),d=JSON.parse(l.details);let code=d.displayCode||d.code;if(!/^[A-Z0-9]{3}$/.test(code||'')||(code==='LOG'||[...existing,...newLuts].some(other=>{const od=JSON.parse(other.details);return (od.displayCode||od.code)===code&&!canShareCode(l,other);}))) {for(let n=0;n<46656;n++){const value=n.toString(36).toUpperCase().padStart(3,'0');if(!usedCodes.has(value)){code=value;break;}}d.displayCode=code;}usedCodes.add(code);maps.luts.set(l.id,id);assetMap.set(l.asset,`luts/${id}.cube`);newLuts.push({...l,id,asset:assetMap.get(l.asset),details:JSON.stringify(d)});}
 for(const f of files.keys())if(!assetMap.has(f)){const match=f.match(/^gallery\/([^/]+)\/(.+)$/);let galleryName=match?.[2];if(match){const original=data.luts.find(l=>JSON.parse(l.details).code+'.jpg'===galleryName),current=original&&(existing.find(l=>l.id===maps.luts.get(original.id))||newLuts.find(l=>l.id===maps.luts.get(original.id)));if(current&&JSON.parse(current.details).legacy)galleryName=JSON.parse(current.details).code+'.jpg';}assetMap.set(f,match?`gallery/${maps.scenes.get(match[1])||randomUUID()}/${galleryName}`:`${f.split('/')[0]}/${randomUUID()}${path.extname(f)}`);}
 function remap(value){if(typeof value==='string'){const prefix=value.startsWith('assets/')?'assets/':'';return assetMap.has(value.slice(prefix.length))?prefix+assetMap.get(value.slice(prefix.length)):value;}if(Array.isArray(value))return value.map(remap);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,remap(v)]));return value;}
 try{
  for(const [old,next]of assetMap){signal?.throwIfAborted();if(existing.some(l=>l.asset===next))continue;const target=path.join(store.root,next);await fsp.mkdir(path.dirname(target),{recursive:true});await fsp.copyFile(sourceFile(sourceRoot,old),target,fs.constants.COPYFILE_EXCL);created.push(target);}
  signal?.throwIfAborted();store.change(()=>{
   store.db.run('INSERT INTO projects VALUES (?,?)',[projectId,data.project.name]);
   for(const c of data.clips){const m=remap(JSON.parse(c.metadata));const source=m.librarySource?path.join(store.root,m.librarySource):'';if(source&&fs.existsSync(source))m.fingerprint=media.fingerprint(source);store.db.run('INSERT INTO clips VALUES (?,?,?,?,?,?)',[maps.clips.get(c.id),projectId,c.name,source,c.profile,JSON.stringify(m)]);}
   for(const s of data.scenes)store.db.run('INSERT INTO scenes(id,project_id,clip_id,name,frame_index,pts,time_base,asset,thumb,sha256,tags,deleted,details) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[maps.scenes.get(s.id),projectId,maps.clips.get(s.clip_id),s.name,s.frame_index,s.pts,s.time_base,assetMap.get(s.asset),assetMap.get(s.thumb),s.sha256,s.tags,s.deleted,JSON.stringify(remap(JSON.parse(s.details)))]);
   for(const c of data.collections)store.db.run('INSERT INTO collections VALUES (?,?,?)',[maps.collections.get(c.id),projectId,c.name]);
   for(const m of data.memberships)store.db.run('INSERT INTO memberships VALUES (?,?)',[maps.scenes.get(m.scene_id),maps.collections.get(m.collection_id)]);
   for(const o of data.scene_orders)store.db.run('INSERT INTO scene_orders VALUES (?,?,?,?)',[projectId,maps.collections.get(o.scope)||'',maps.scenes.get(o.scene_id),o.position]);
   for(const o of data.collection_orders)store.db.run('INSERT INTO collection_orders VALUES (?,?,?)',[projectId,maps.collections.get(o.collection_id),o.position]);
   let position=store.query('SELECT COALESCE(MAX(position),-1)+1 AS n FROM luts')[0].n;for(const l of newLuts)store.db.run('INSERT INTO luts(id,name,original_name,sha256,asset,size,input,output,favourite,details,position) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[l.id,l.name,l.original_name,l.sha256,l.asset,l.size,l.input,l.output,0,l.details,position++]);
   if(data.settings){const state=JSON.parse(data.settings.state),lutNames=new Map(data.luts.map(l=>{const original=JSON.parse(l.details).legacy?l.original_name:`${l.id}.cube`,current=store.one('SELECT * FROM luts WHERE id=?',[maps.luts.get(l.id)]);return [original,JSON.parse(current.details).legacy?current.original_name:`${current.id}.cube`];}));state.lutOrder=(state.lutOrder||data.luts.map(l=>l.id)).map(id=>maps.luts.get(id)).filter(Boolean);state.scene=maps.scenes.get(state.scene)||'';state.sceneCollection=maps.collections.get(state.sceneCollection)||'';state.sceneOrder=(state.sceneOrder||[]).map(id=>maps.scenes.get(id)).filter(Boolean);state.selected=lutNames.get(state.selected)||'';state.reference=lutNames.get(state.reference)||'';state.favourites=(state.favourites||[]).map(n=>lutNames.get(n)).filter(Boolean);state.adjustments=Object.fromEntries(Object.entries(state.adjustments||{}).map(([id,value])=>[maps.scenes.get(id),value]).filter(([id])=>id));store.db.run('INSERT INTO ui_state VALUES (?,?,?)',[projectId,randomUUID(),JSON.stringify(state)]);}
  });return {projectId,name:data.project.name};
 }catch(e){for(const file of created)await fsp.unlink(file).catch(()=>{});throw e;}
}
async function open(store,file,signal){const folder=path.join(store.root,'staging',randomUUID());await fsp.mkdir(folder);try{const names=await extract(file,folder,signal),data=JSON.parse(await fsp.readFile(path.join(folder,'project.json'),'utf8'));const files=validate(data);if(names.size!==files.size+1||[...files.keys()].some(f=>!names.has(f)))throw Error('Project contents differ from its manifest.');return await importData(store,data,folder,signal);}finally{await fsp.rm(folder,{recursive:true,force:true});}}
function backups(store){return fs.readdirSync(path.join(store.root,'backups')).filter(id=>/^Library-\d+$/.test(id)&&fs.existsSync(path.join(store.root,'backups',id,'library.sqlite'))).sort().reverse().map(id=>{const folder=path.join(store.root,'backups',id),db=new store.SQL.Database(fs.readFileSync(path.join(folder,'library.sqlite')));try{return {id,date:new Date(Number(id.slice(8))).toISOString(),projects:rows(db,'SELECT * FROM projects')};}catch{return null;}finally{db.close();}}).filter(Boolean);}
async function restore(store,id,projectId,signal){if(!/^Library-\d+$/.test(id))throw Error('Choose an available backup.');const root=path.join(store.root,'backups',id),db=new store.SQL.Database(fs.readFileSync(path.join(root,'library.sqlite')));try{if(db.exec('PRAGMA integrity_check')[0].values[0][0]!=='ok')throw Error('Backup integrity check failed.');const data=await manifest({db,root},projectId,signal);return await importData(store,data,root,signal);}finally{db.close();}}
module.exports={save,open,backups,restore,manifest,importData};
