'use strict';
(()=>{
 const el=id=>document.getElementById(id),call=(...args)=>window.LUTLibrary.call(...args),make=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 let rows=[],kind,active=0,busy=false,saving=false,request,requestId,stopTask,generation=0,reloadOnClose=false,sceneId,library,portReview=false,automatic=false;
 const preferred=()=>localStorage.getItem('lut-ai-provider')==='codex'?'codex':'claude-code';
 const status=text=>el('batch-status').textContent=text;
 const fields=()=>[['name','Name',160],...(kind==='lut'&&!portReview?[['code','Abbreviation',3],['maker','Creator',160]]:[]),['description','Description',1000],['tags','Tags',1000],...(kind==='lut'&&!portReview?[['input','Expected recording profile'],['output','Output profile']]:[])];
 function original(item){const d=JSON.parse(item.details);return {name:item.name,description:kind==='scene'?d.description||'':d.description?.text||'',tags:kind==='scene'?item.tags:d.tags||'',...(kind==='lut'?{code:d.displayCode||d.code||'',maker:d.maker||'',input:item.input,output:item.output}:{})};}
 function controls(){const selected=rows.filter(r=>r.checked);el('batch-count').textContent=`${selected.length} of ${rows.length} selected`;el('batch-select-all').disabled=busy||saving;el('batch-generate').disabled=busy||saving||!selected.length;el('batch-save').disabled=busy||saving||!selected.length;el('batch-provider').disabled=busy||saving;el('batch-stop').hidden=!busy;el('batch-close').disabled=saving;}
 function drawList(){el('batch-list').replaceChildren(...rows.map((row,index)=>{const n=make('div',undefined,'batch-item'),check=make('input');check.type='checkbox';check.checked=row.checked;check.disabled=busy||saving;check.setAttribute('aria-label','Include '+row.item.name);check.addEventListener('change',()=>{row.checked=check.checked;controls();});const button=make('button');button.type='button';button.setAttribute('aria-pressed',String(index===active));button.append(make('span',row.values.name),make('small',row.error||row.note||'Review details'));button.addEventListener('click',()=>{active=index;drawList();drawFields();});n.append(check,button);return n;}));controls();}
 function drawFields(){
  const row=rows[active],box=el('batch-fields');box.replaceChildren();if(!row)return;
  const image=make('img');image.alt=kind==='scene'?'Original scene':'LUT applied to the current scene';image.src=kind==='scene'?`assets/${row.item.thumb}`:`previews/${reference(row)}/${row.item.id}`;image.hidden=true;image.addEventListener('load',()=>image.hidden=false);image.addEventListener('error',()=>{image.hidden=true;});box.append(image);
  for(const [key,label,max]of fields()){
   const group=make('div'),heading=make('label',undefined,'library-checkbox'),check=make('input');check.type='checkbox';check.checked=row.use.has(key);check.disabled=busy||saving;check.setAttribute('aria-label','Use '+label);check.addEventListener('change',()=>check.checked?row.use.add(key):row.use.delete(key));heading.append(check,make('span',label));
   const input=make(key==='description'?'textarea':['input','output'].includes(key)?'select':'input',undefined,'library-input');input.dataset.field=key;input.setAttribute('aria-label',label);if(max)input.maxLength=max;if(key==='description')input.rows=2;
   if(['input','output'].includes(key))for(const [value,title]of window.LUTLibrary.profiles)input.append(new Option(title,value));input.value=row.values[key];input.disabled=busy||saving;
   input.addEventListener('input',()=>{row.values[key]=input.value;row.use.add(key);check.checked=true;drawList();if(['input','output'].includes(key))drawFields();});group.append(heading,input);box.append(group);
  }
  if(kind==='lut'){const choices=matches(row),label=make('label','Scene for AI preview'),select=make('select',undefined,'library-input');select.setAttribute('aria-label','Scene for AI preview');if(!choices.length)select.append(new Option('No matching scene — confirm profiles or import matching footage',''));else for(const s of choices)select.append(new Option(s.name,s.id));select.value=reference(row)||'';select.disabled=busy||saving;select.addEventListener('change',()=>{row.reference=select.value;drawFields();});label.append(select);box.append(label);const button=make('button','Save profiles & continue');button.hidden=portReview;button.type='button';button.disabled=busy||saving;button.addEventListener('click',async()=>{let saved=false;saving=true;controls();try{await saveProfiles();saved=true;status('Profiles saved. Your name and description drafts are still here.');}catch(e){status(e.message);}finally{saving=false;drawList();drawFields();}if(saved&&automatic)await automaticallySuggest();});box.append(button);}
 }
 function matches(row){const input=row.use.has('input')?row.values.input:row.original.input,output=row.use.has('output')?row.values.output:row.original.output;return library.scenes.filter(s=>s.project_id===window.LUTProduct.boot.projectId&&((output==='rec709'&&library.clips.find(c=>c.id===s.clip_id)?.profile===input)||(JSON.parse(row.item.details).legacy&&input==='unknown'&&output==='unknown'&&library.clips.find(c=>c.id===s.clip_id)?.profile==='sony-slog3-sgamut3cine')));}
 function reference(row){const valid=matches(row);return valid.find(s=>s.id===row.reference)?.id||valid.find(s=>s.id===sceneId)?.id||valid[0]?.id;}
 async function saveProfiles(){const selected=rows.filter(r=>r.checked),items=selected.map(row=>({id:row.item.id,fields:Object.fromEntries(['input','output'].filter(k=>row.use.has(k)&&row.values[k]!==row.original[k]).map(k=>[k,row.values[k]])),expectedRevision:row.revision})).filter(i=>Object.keys(i.fields).length);if(!items.length)return;await call('updateBatch',{kind:'lut',items});const latest=await call('reviewItems',{kind:'lut',ids:items.map(r=>r.id)});for(const {item,revision}of latest){const row=rows.find(r=>r.item.id===item.id);row.item=item;row.revision=revision;row.original.input=item.input;row.original.output=item.output;}reloadOnClose=true;}
 async function open({kind:next,ids,afterImport=false,portReview:ported=false,autoAI=false,provider}){
  if(el('batch-dialog').open||busy||saving)return;
  try{kind=next;portReview=ported;automatic=afterImport||autoAI;sceneId=window.LUTProduct.getSelection().scene;library=await call('state');const result=await call('reviewItems',{kind,ids,projectId:window.LUTProduct.boot.projectId});rows=result.map(({item,revision})=>{const values=original(item);return {item,revision,values,original:{...values},checked:true,use:new Set(Object.keys(values).filter(k=>!portReview||['name','description','tags'].includes(k))),aiFields:new Set()};});active=0;generation++;reloadOnClose=afterImport;el('batch-title').textContent=`${portReview?'Review converted':'Review'} ${rows.length} ${kind==='scene'?'scene':'LUT'}${rows.length===1?'':'s'}`;el('batch-provider').value=provider||preferred();el('batch-context').textContent=kind==='scene'?'A connected AI tool automatically drafts details from the selected original previews. Camera settings and recording profiles stay unchanged.':'A connected AI tool automatically drafts details using original/LUT previews from matching footage. Confirm unknown LUT profiles below; AI suggestions stay editable until you save.';status(afterImport?'Imported and saved. Review details now, or close to keep the current names.':'Edit the selected items, then save together. Uncheck any field you want to keep.');drawList();drawFields();el('batch-dialog').showModal();if(portReview)el('batch-context').textContent='Your linked 33-point copies are saved. AI can review names/descriptions using matching footage. Colour conversion, profiles and shared abbreviations stay fixed; camera calibration is not established.';if(automatic)await automaticallySuggest();}
  catch(error){document.getElementById('library-message').textContent=error.message;if(afterImport){sessionStorage.setItem('library-message',error.message+' Imported items are still saved.');await window.LUTLibrary.reload();}}
 }
 async function automaticallySuggest(){
  if(busy||saving||!el('batch-dialog').open)return;const own=++generation;busy=true;drawList();drawFields();status('Checking your AI connection…');
  try{const connections=await call('aiStatus');if(own!==generation||!el('batch-dialog').open)return;const preferredTool=connections.find(c=>c.id===el('batch-provider').value&&c.ready),tool=preferredTool||connections.find(c=>c.ready);busy=false;
   if(!tool){drawList();drawFields();status('Imported items are saved. Connect an AI tool in Library → AI tools for automatic suggestions, or edit manually.');return;}
   el('batch-provider').value=tool.id;
   if(kind==='lut'&&!rows.some(r=>r.checked&&reference(r))){drawList();drawFields();status('AI is connected. Confirm the LUT profiles and save them to automatically suggest details from matching footage.');return;}
   await generate();
  }catch(e){if(own===generation){busy=false;drawList();drawFields();status('AI is unavailable. Imported items stay saved and editable. '+e.message);}}
 }
 async function generate(){
  if(busy||saving)return;if(kind==='lut'){saving=true;controls();try{await saveProfiles();}catch(e){status(e.message);return;}finally{saving=false;controls();}}const own=++generation,selected=rows.filter(r=>r.checked),provider=el('batch-provider').value;localStorage.setItem('lut-ai-provider',provider);busy=true;drawList();drawFields();let completed=0;
  try{for(const row of selected){if(own!==generation)break;row.error='';if(kind==='lut'&&!reference(row)){row.error='No matching scene. Confirm both LUT profiles and choose matching footage.';drawList();continue;}row.note='Asking AI…';drawList();status(`Suggesting details ${++completed} / ${selected.length}. Sends selected previews to ${provider==='codex'?'Codex':'Claude Code'}.`);request=new AbortController();requestId=crypto.randomUUID();
    try{const result=await call('aiSuggest',{kind,id:row.item.id,sceneId:kind==='lut'?reference(row):sceneId,provider,requestId,reservedCodes:rows.filter(r=>r!==row).map(r=>r.values.code).filter(Boolean)},request.signal);if(own!==generation)break;if(result.baseRevision!==row.revision)throw Error('This item changed. Close and reopen the review.');
     row.source=result.source;for(const [key,value]of Object.entries(result.suggestion)){if(portReview&&!['name','description','tags'].includes(key))continue;row.values[key]=value;row.aiFields.add(key);row.use.add(key);}row.note='Suggestion ready';
    }catch(error){if(own!==generation)break;row.error=error.message;row.note='';}finally{request=undefined;requestId=undefined;}
    drawList();drawFields();
   }}finally{if(own===generation){busy=false;drawList();drawFields();status(rows.some(r=>r.error)?'Some suggestions could not be generated. Review successful suggestions or edit details manually.':'Review suggestions and choose which fields to save. Nothing has changed yet.');}}
 }
 async function stop(){if(stopTask)return stopTask;if(!busy)return;const own=++generation,id=requestId;request?.abort();request=undefined;requestId=undefined;stopTask=(async()=>{try{if(id)await call('cancel',{requestId:id});}catch{}if(own!==generation)return;busy=false;for(const row of rows)if(row.note==='Asking AI…')row.note='Cancelled';drawList();drawFields();status('Stopped. Completed suggestions remain available to review; nothing was saved.');})();try{await stopTask;}finally{stopTask=undefined;}}
 async function save(){
  if(busy||saving)return;
  const items=rows.filter(r=>r.checked).map(row=>{const changes=Object.fromEntries([...row.use].filter(key=>row.values[key]!==row.original[key]).map(key=>[key,row.values[key]]));return {id:row.item.id,fields:changes,expectedRevision:row.revision,...(Object.keys(changes).some(key=>row.aiFields.has(key))?{aiSource:row.source}:{})};}).filter(item=>Object.keys(item.fields).length);
  if(!items.length){status('No detail changes selected. Close to keep the current details.');return;}
  saving=true;drawList();drawFields();status('Saving reviewed details…');
  try{await call('updateBatch',{kind,projectId:window.LUTProduct.boot.projectId,items});reloadOnClose=true;el('batch-dialog').close();}catch(error){status(error.message);}finally{saving=false;drawList();drawFields();}
 }
 el('batch-generate').addEventListener('click',generate);el('batch-stop').addEventListener('click',stop);el('batch-save').addEventListener('click',save);el('batch-close').addEventListener('click',()=>el('batch-dialog').close());
 el('batch-select-all').addEventListener('click',()=>{const value=!rows.every(r=>r.checked);rows.forEach(r=>r.checked=value);drawList();});
 el('batch-dialog').addEventListener('cancel',e=>{if(saving)e.preventDefault();});
 el('batch-dialog').addEventListener('close',async()=>{if(busy)await stop();generation++;if(reloadOnClose){reloadOnClose=false;await window.LUTLibrary.reload();}});
 window.LUTBatchReview={open};
})();
