'use strict';
(()=>{
 const el=id=>document.getElementById(id),boot=window.LUTProduct.boot;
 let library,tab='scenes',collectionId='',editingScene,editingLut,clip,decoded,marks=[],wanted,loadingFrame=false,uploadController,pollTimer,frameSession=0,frameRequest,frameTask,displayedFrame,candidateRequest;
 const selected={scenes:new Set(),luts:new Set()},selecting={scenes:false,luts:false};
 const profiles=boot.profiles?.map(p=>[p.id,p.label])||[['unknown','[Unverified] — confirm profile'],['sony-slog3-sgamut3cine','Sony S-Log3 / S-Gamut3.Cine'],['rec709','Rec.709'],['apple-log','Apple Log / BT.2020'],['apple-log2','Apple Log 2 / Apple Wide Gamut'],['hlg-bt2020','HDR HLG / BT.2020'],['canon-clog3-cinema-gamut','Canon C-Log3 / Cinema Gamut'],['panasonic-vlog-vgamut','Panasonic V-Log / V-Gamut'],['arri-logc3-wide-gamut3','ARRI LogC3 / Wide Gamut 3']];
 const node=(tag,text,className)=>{const item=document.createElement(tag);if(text!==undefined)item.textContent=text;if(className)item.className=className;return item;};
 const options=(select,rows,value)=>{select.replaceChildren(...rows.map(([id,label])=>{const option=node('option',label);option.value=id;return option;}));if(value!==undefined)select.value=value;};
 const message=text=>{el('library-message').textContent=text;sessionStorage.setItem('library-message',text);};
 const safe=async work=>{try{return await work();}catch(error){message(error.message);if(el('clip-dialog').open)el('import-status').textContent=error.message;}};
 async function call(method,payload={},signal){const response=await fetch('api/call',{method:'POST',signal,headers:{'Content-Type':'application/json','X-LUT-Token':boot.token},body:JSON.stringify({method,payload:{projectId:boot.projectId,...payload}})});const value=await response.json();if(!response.ok||value.ok===false)throw new Error(value.error||'Library operation failed.');return value.data;}
 async function reload(flush=true){if(flush)await window.LUTProduct.flush?.();if(!el('library-panel').hidden)sessionStorage.setItem('library-reopen',tab);location.reload();}
 const scenes=()=>library.scenes.filter(s=>s.project_id===boot.projectId);
 const groups=()=>library.collections.filter(g=>g.project_id===boot.projectId);
 function time(pts,base){const [n,d]=base.split('/').map(Number),seconds=Number(pts)*n/d;return `${Math.floor(seconds/60)}:${(seconds%60).toFixed(3).padStart(6,'0')}`;}
 async function refresh(){library=await call('state');draw();}
 function showTab(next){tab=next;el('library-lut-rights').hidden=tab!=='luts';for(const name of ['scenes','clips','luts'])el('library-'+name).hidden=name!==tab;for(const button of document.querySelectorAll('.library-tabs button'))button.setAttribute('aria-pressed',String(button.dataset.tab===tab));}
 function draw(){
  window.LUTScenePicker?.setLibrary(library);
  options(el('library-project'),library.projects.map(p=>[p.id,p.name]),boot.projectId);
  options(el('library-collection'),[['','All scenes'],...groups().map(g=>[g.id,g.name])],collectionId);
  options(el('import-collection'),[['','No collection'],...groups().map(g=>[g.id,g.name])],el('import-collection').value);
  drawScenes();drawLuts();
  el('library-clip-list').replaceChildren(...library.clips.filter(c=>c.project_id===boot.projectId&&!c.legacy).map(c=>{const button=node('button');const text=node('span',c.name);text.append(node('small',(profiles.find(p=>p[0]===c.profile)?.[1]||'[Unverified]')+(c.linked?' · linked original':'')));button.append(text);button.addEventListener('click',()=>safe(()=>openClip(c.id)));return button;}));
  for(const action of ['undo','redo']){const entry=library.history?.[action],button=el('library-'+action);button.disabled=!entry;button.title=entry?`${action==='undo'?'Undo':'Redo'}: ${entry.label}`:`Nothing to ${action}`;}
 }
 function drawScenes(){const search=el('library-search').value.toLowerCase(),selected=window.LUTProduct.getSelection().scene;el('library-scene-list').replaceChildren(...scenes().sort((a,b)=>{const ids=window.LUTScenePicker?.orderIds(collectionId)||[];return ids.indexOf(a.id)-ids.indexOf(b.id);}).filter(s=>(!collectionId||library.memberships.some(m=>m.scene_id===s.id&&m.collection_id===collectionId))&&`${s.name} ${s.tags}`.toLowerCase().includes(search)).map(s=>{const button=node('button');button.setAttribute('aria-pressed',String(s.id===selected));const image=node('img');image.src=`assets/${s.thumb}`;image.alt='';const text=node('span',s.name);text.append(node('small',s.tags||`${time(s.pts,s.time_base)} · ${s.id.startsWith('legacy-')?'saved scene':'frame '+(s.frame_index+1)}`));button.append(image,text);selectable(button,s,'scenes',()=>{window.LUTProduct.selectScene(s.id);drawScenes();});return button;}));el('library-delete-collection').hidden=!collectionId;}
 function portIcon(lut){const details=JSON.parse(lut.details);if(!details.adaptation)return;const badge=node('span',undefined,'ported-indicator');badge.innerHTML='<svg viewBox="0 0 16 16" aria-hidden="true"><rect x="5" y="5" width="8" height="8" rx="1"/><path d="M3 10H2V2h8v1"/></svg>';badge.title='Ported copy · '+details.adaptation.sourceName;badge.setAttribute('aria-label','Ported copy of '+details.adaptation.sourceName);return badge;}
 function drawLuts(){const search=el('library-lut-search').value.toLowerCase();el('library-lut-list').replaceChildren(...library.luts.filter(l=>l.name.toLowerCase().includes(search)).map(l=>{const button=node('button'),text=node('span',`${l.favourite?'★ ':''}${l.name}`);text.append(node('small',`${l.size}-point · ${l.input==='unknown'||l.output==='unknown'?'[Unverified] profiles':JSON.parse(l.details).adaptation?'Profile-adapted copy':'Profiles supplied by you'}`));button.append(text);const badge=portIcon(l);if(badge)button.append(badge);selectable(button,l,'luts',()=>openLut(l));return button;}));}
 function selectable(button,item,type,choose){
  if(selecting[type]){const checked=selected[type].has(item.id),check=node('span',checked?'☑':'□','library-select-check');check.setAttribute('aria-hidden','true');button.setAttribute('aria-label','Select '+item.name);button.setAttribute('aria-pressed',String(checked));button.prepend(check);button.classList.toggle('library-selected',checked);}
  button.addEventListener('click',()=>{if(selecting[type]){selected[type].has(item.id)?selected[type].delete(item.id):selected[type].add(item.id);type==='scenes'?drawScenes():drawLuts();selectionControls(type);}else choose();});
 }
 function selectionControls(type){
  const count=selected[type].size,review=el('library-review-'+type);
  el('library-select-'+type).textContent=selecting[type]?'Done':'Select';review.disabled=!count;
  if(type==='luts'){
   review.hidden=!count;const convert=el('library-port-luts');convert.hidden=!count;
   for(const [button,label] of [[review,`Edit details for ${count} selected LUT${count===1?'':'s'}`],[convert,`Convert ${count} selected LUT${count===1?'':'s'} to a device`]]){button.title=label;button.setAttribute('aria-label',label);}
  }else{review.hidden=!selecting[type];review.textContent=count?`Review ${count} selected`:'Review selected';}
 }
 for(const type of ['scenes','luts']){
  el('library-select-'+type).addEventListener('click',()=>{selecting[type]=!selecting[type];if(!selecting[type])selected[type].clear();selectionControls(type);type==='scenes'?drawScenes():drawLuts();});
  el('library-review-'+type).addEventListener('click',()=>window.LUTBatchReview.open({kind:type==='scenes'?'scene':'lut',ids:[...selected[type]]}));
 }
 async function open(){el('library-panel').hidden=false;el('library-message').textContent=sessionStorage.getItem('library-message')||'';await refresh();}
 async function askName(title,value=''){el('library-name-title').textContent=title;el('library-name-input').value=value;el('library-name-dialog').returnValue='';return new Promise(resolve=>{el('library-name-dialog').addEventListener('close',()=>resolve(el('library-name-dialog').returnValue==='save'?el('library-name-input').value:null),{once:true});el('library-name-dialog').showModal();});}
 function resetFramePicker(){frameSession++;candidateRequest?.abort();candidateRequest=undefined;frameRequest?.abort();frameRequest=undefined;frameTask=undefined;decoded=undefined;displayedFrame=undefined;wanted=undefined;loadingFrame=false;el('import-mark').disabled=true;}
 function previewLoading(text){el('import-loading').textContent=text;el('import-loading').hidden=!text;}
 function frameLabel(value){return `${time(value.pts,value.timeBase)} · frame ${value.index+1} / ${clip.frameCount}`;}
 async function openClip(id){
  resetFramePicker();const session=frameSession;const selected=await call('clip',{id});if(session!==frameSession)return;clip=selected;marks=[];
  el('import-clip-name').textContent=clip.name;el('import-profile').value=clip.profile;el('import-metadata').textContent=`${clip.width} × ${clip.height} · ${clip.codec} · ${clip.pixelFormat}. Decoded range: ${clip.range}; matrix: ${clip.matrix}. ${clip.linked?'Linked original. ':''}${clip.metadataWarning?clip.metadataWarning+' ':''}Confirm any unverified recording profile.`;el('import-candidates').replaceChildren();el('import-candidates').hidden=true;el('import-suggest-frames').disabled=false;
  el('import-scrubber').max=clip.frameCount-1;el('import-scrubber').value=0;el('import-preview').hidden=true;el('import-preview').removeAttribute('src');el('import-frame-time').textContent='';el('import-status').textContent='';previewLoading('Loading frame preview…');renderMarks();el('clip-dialog').showModal();requestFrame(0);
 }
 function requestFrame(index){if(!clip||!el('clip-dialog').open)return;wanted=Math.max(0,Math.min(clip.frameCount-1,index));el('import-scrubber').value=wanted;decoded=undefined;el('import-mark').disabled=true;el('import-frame-time').textContent=`Loading frame ${wanted+1} / ${clip.frameCount}…`;if(el('import-preview').hidden)previewLoading('Preparing fast frame previews…');loadFrame();}
 function loadFrame(){
  if(frameTask||wanted===undefined)return;const session=frameSession;
  const work=(async()=>{loadingFrame=true;
   try{while(session===frameSession&&wanted!==undefined&&el('clip-dialog').open){
    const index=wanted,id=clip.id;wanted=undefined;frameRequest=new AbortController();
    const value=await call('framePreview',{clipId:id,index},frameRequest.signal);if(session!==frameSession||!el('clip-dialog').open)return;
    const image=new Image();image.src=value.preview;await image.decode();if(session!==frameSession||!el('clip-dialog').open)return;
    // Show completed previews during a drag, while only allowing the settled frame to be marked.
    el('import-preview').src=value.preview;el('import-preview').hidden=false;previewLoading('');displayedFrame=value;
    el('import-frame-time').textContent=frameLabel(value)+(wanted!==undefined?` · loading frame ${wanted+1}…`:'');
    if(wanted===undefined){decoded=value;el('import-mark').disabled=false;}
   }}catch(error){if(session===frameSession&&error.name!=='AbortError'){wanted=undefined;decoded=undefined;el('import-mark').disabled=true;el('import-status').textContent=error.message;previewLoading(el('import-preview').hidden?'Preview unavailable. Move the slider to retry.':'');}}
   finally{if(session===frameSession){loadingFrame=false;frameRequest=undefined;frameTask=undefined;if(wanted!==undefined)loadFrame();}}
  })();frameTask=work;return work;
 }
 el('clip-dialog').addEventListener('close',()=>{resetFramePicker();el('import-candidates').replaceChildren();previewLoading('');el('import-preview').hidden=true;el('import-preview').removeAttribute('src');});
 function renderMarks(){el('import-mark-count').textContent=marks.length?`${marks.length} selected frame${marks.length===1?'':'s'}`:'No frames selected';el('import-save').disabled=!marks.length;el('import-marks').replaceChildren(...marks.map(mark=>{const card=node('div',undefined,'import-mark'),image=node('img');image.src=mark.preview;image.alt=`Frame ${mark.index+1}`;const input=node('input',undefined,'library-input');input.value=mark.name;input.maxLength=160;input.setAttribute('aria-label',`Name frame ${mark.index+1}`);input.addEventListener('input',()=>mark.name=input.value);const remove=node('button','×');remove.setAttribute('aria-label',`Unmark frame ${mark.index+1}`);remove.addEventListener('click',()=>{marks=marks.filter(m=>m.index!==mark.index);renderMarks();});card.append(image,input,node('small',time(mark.pts,mark.timeBase)),remove);return card;}));}
 async function upload(files,type){
  if(!files.length)return;uploadController=new AbortController();let first;const errors=[],imported=[];
  const videos=type==='clip'?files.filter(file=>/\.(mp4|mov|mxf|mkv|mts|m2ts|avi|webm)$/i.test(file.name)):files;
  try{for(const file of videos){const response=await fetch(`api/upload/${type}?project=${boot.projectId}&name=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'X-LUT-Token':boot.token,'Content-Type':'application/octet-stream'},body:file,signal:uploadController.signal});const result=await response.json();if(!response.ok||!result.ok){errors.push(`${file.name}: ${result.error}`);continue;}first??=result.data.id;if(!result.data.duplicate)imported.push(result.data.id);
    if(type==='clip'){const relative=file.webkitRelativePath||file.name,expected=relative.replace(/\.[^.]+$/,'M01.xml').toLowerCase(),sidecars=files.filter(candidate=>(candidate.webkitRelativePath||candidate.name).toLowerCase()===expected);if(sidecars.length===1){try{await call('cameraSidecar',{id:result.data.id,filename:sidecars[0].name,xml:await sidecars[0].text()},uploadController.signal);}catch(error){errors.push(`${sidecars[0].name}: ${error.message}`);}}}
   }
   await refresh();if(errors.length)message(errors.join('\n'));else message(type==='clip'?'Recorded camera information read. Check any unverified profile, then mark your scenes.':'LUTs imported; matching content was deduplicated. Confirm their profiles in Library.');
   if(type==='clip'&&first)await openClip(first);if(type==='lut'){if(imported.length)await window.LUTBatchReview.open({kind:'lut',ids:imported,afterImport:true});else await reload();}
  }finally{uploadController=undefined;}
 }
 function openScene(){const selected=window.LUTProduct.getSelection().scene;editingScene=library.scenes.find(s=>s.id===selected);if(!editingScene){message('Choose a scene first.');return;}el('edit-scene-name').value=editingScene.name;el('edit-scene-tags').value=editingScene.tags;el('edit-scene-description').value=JSON.parse(editingScene.details).description||'';const c=library.clips.find(c=>c.id===editingScene.clip_id);el('edit-scene-profile').value=c.profile;el('edit-scene-groups').replaceChildren(...groups().map(group=>{const label=node('label',undefined,'library-checkbox'),input=node('input');input.type='checkbox';input.value=group.id;input.checked=library.memberships.some(m=>m.scene_id===selected&&m.collection_id===group.id);label.append(input,node('span',group.name));return label;}));const details=JSON.parse(editingScene.details);el('edit-scene-provenance').textContent=`${details.demo?'Creator-provided demo frame.':details.legacy?'Migrated saved scene. Original selection and adjustments retained.':'Captured from the original clip.'} ${time(editingScene.pts,editingScene.time_base)} · frame ${editingScene.frame_index+1}. ${details.timingProvenance||''}${details.sourceProvenance?' Demo by '+details.sourceProvenance.creator+'. '+details.sourceProvenance.profile+' is documented by the creator; original camera profile tags are [Unverified].':''}`;el('edit-scene-export').href=`export/still/${selected}/original`;el('scene-dialog').showModal();}
 function openLut(lut){editingLut=lut;const details=JSON.parse(lut.details);el('edit-lut-code').value=details.displayCode||details.code||'';el('edit-lut-maker').value=details.maker||'';el('edit-lut-description').value=details.description?.text||'';el('edit-lut-tags').value=details.tags||'';el('edit-lut-name').value=lut.name;el('edit-lut-input').value=lut.input;el('edit-lut-output').value=lut.output;el('edit-lut-favourite').checked=!!lut.favourite;el('edit-lut-provenance').textContent=details.adaptation?`${lut.size}-point ported version for ${profiles.find(p=>p[0]===lut.input)?.[1]||lut.input} of ${details.adaptation.sourceName}. Original LUT kept unchanged. Camera-to-camera match [Unverified] until tested on paired footage.`:`${lut.original_name} · ${lut.size}-point grid. Imported contents preserved. ${details.legacy?'Your original Sony library remains available for Sony S-Log3 / S-Gamut3.Cine footage. Individual input/output labels remain [Unverified] until confirmed.':''}`;el('edit-lut-export').href=`export/lut/${lut.id}`;el('lut-dialog').showModal();}
 for(const id of ['import-profile','edit-scene-profile','edit-lut-input','edit-lut-output'])options(el(id),profiles);
 el('library-open').addEventListener('click',()=>safe(open));el('library-close').addEventListener('click',()=>el('library-panel').hidden=true);
 for(const button of document.querySelectorAll('.library-tabs button'))button.addEventListener('click',()=>showTab(button.dataset.tab));
 for(const [button,dialog]of [['clip-dialog-close','clip-dialog'],['scene-dialog-close','scene-dialog'],['lut-dialog-close','lut-dialog']])el(button).addEventListener('click',()=>el(dialog).close());
 el('library-project').addEventListener('change',()=>safe(async()=>{await window.LUTProduct.flush?.();location.href=`index.html?project=${el('library-project').value}`;}));
 el('library-rename-project').addEventListener('click',()=>safe(async()=>{const project=library.projects.find(p=>p.id===boot.projectId),label=await askName('Rename project',project.name);if(label!==null){library=await call('renameProject',{name:label,expectedName:project.name});draw();message('Project renamed.');}}));
 el('library-new-project').addEventListener('click',()=>safe(async()=>{const label=await askName('New project');if(label){await window.LUTProduct.flush?.();const result=await call('project',{name:label});location.href=`index.html?project=${result.projects.at(-1).id}`;}}));
 el('library-new-collection').addEventListener('click',()=>safe(async()=>{const label=await askName('New collection');if(label){library=await call('collection',{projectId:boot.projectId,name:label});draw();}}));
 el('library-delete-collection').addEventListener('click',()=>safe(async()=>{library=await call('deleteCollection',{id:collectionId});collectionId='';draw();message('Collection removed. Its scenes are still saved.');}));
 el('library-collection').addEventListener('change',()=>{collectionId=el('library-collection').value;drawScenes();});el('library-search').addEventListener('input',drawScenes);el('library-lut-search').addEventListener('input',drawLuts);
 el('library-port-luts').addEventListener('click',()=>{if(selected.luts.size)window.LUTPorting.open({ids:[...selected.luts]});});
 el('edit-lut-port').addEventListener('click',()=>{el('lut-dialog').close();window.LUTPorting.open({ids:[editingLut.id]});});
 el('library-link-clips').hidden=boot.canLinkOriginals===false;
 el('library-link-clips').addEventListener('click',()=>safe(async()=>{const result=await call('linkClips');await refresh();message(result.errors.length?result.errors.join('\n'):result.imported.length?'Originals linked. Saved scenes will stay in the library.':'Selection cancelled.');if(result.imported.length)await openClip(result.imported[0].id);}));
 el('import-suggest-frames').addEventListener('click',()=>safe(async()=>{const id=clip.id,session=frameSession;el('import-suggest-frames').disabled=true;candidateRequest=new AbortController();try{const frames=await call('frameCandidates',{clipId:id,requestId:crypto.randomUUID()},candidateRequest.signal);if(session!==frameSession||!el('clip-dialog').open)return;el('import-candidates').replaceChildren(...frames.map(frame=>{const button=node('button'),img=node('img');img.src=frame.preview;img.alt='Frame at '+time(frame.pts,frame.timeBase);button.append(img,node('small',time(frame.pts,frame.timeBase)));button.addEventListener('click',()=>requestFrame(frame.index));return button;}));el('import-candidates').hidden=false;el('import-status').textContent='Evenly spaced frames. Pick one, then mark it or refine with the scrubber.';}catch(e){if(session===frameSession&&e.name!=='AbortError')throw e;}finally{if(session===frameSession){candidateRequest=undefined;el('import-suggest-frames').disabled=false;}}}));
 el('library-import-clips').addEventListener('click',()=>el('library-clip-files').click());el('library-import-luts').addEventListener('click',()=>el('library-lut-files').click());
 el('library-import-folder').addEventListener('click',()=>el('library-camera-folder').click());el('library-camera-folder').addEventListener('change',event=>safe(async()=>{const files=[...event.target.files];event.target.value='';await upload(files,'clip');}));
 el('library-clip-files').addEventListener('change',event=>safe(async()=>{const files=[...event.target.files];event.target.value='';await upload(files,'clip');}));el('library-lut-files').addEventListener('change',event=>safe(async()=>{const files=[...event.target.files];event.target.value='';await upload(files,'lut');}));
 el('import-profile').addEventListener('change',()=>safe(async()=>{library=await call('setClipProfile',{id:clip.id,value:el('import-profile').value});clip.profile=el('import-profile').value;}));
 el('import-scrubber').addEventListener('input',()=>requestFrame(Number(el('import-scrubber').value)));el('import-prev').addEventListener('click',()=>requestFrame(Number(el('import-scrubber').value)-1));el('import-next').addEventListener('click',()=>requestFrame(Number(el('import-scrubber').value)+1));
 el('import-mark').addEventListener('click',()=>{if(!decoded||loadingFrame)return;if(marks.some(m=>m.index===decoded.index)){el('import-status').textContent='That frame is already selected.';return;}marks.push({...decoded,name:`${clip.name.replace(/\.[^.]+$/,'')} · ${time(decoded.pts,decoded.timeBase)}`});renderMarks();});el('import-clear').addEventListener('click',()=>{marks=[];renderMarks();});
 el('import-save').addEventListener('click',()=>safe(async()=>{if(loadingFrame)throw new Error('Wait for the selected original frame to finish decoding.');const previous=new Set(library.scenes.map(s=>s.id));const result=await call('capture',{clipId:clip.id,indices:marks.map(m=>m.index),names:marks.map(m=>m.name),collectionId:el('import-collection').value});message(`${marks.length} original scene frames saved.`);el('clip-dialog').close();await window.LUTBatchReview.open({kind:'scene',ids:result.scenes.filter(s=>!previous.has(s.id)).map(s=>s.id),afterImport:true});}));
 el('library-scene-details').addEventListener('click',()=>safe(openScene));
 el('edit-scene-save').addEventListener('click',()=>safe(async()=>{await call('updateScene',{id:editingScene.id,name:el('edit-scene-name').value,tags:el('edit-scene-tags').value,collections:[...el('edit-scene-groups').querySelectorAll('input:checked')].map(i=>i.value),description:el('edit-scene-description').value,expectedRevision:editingScene.aiRevision,aiSource:editingScene.aiSource});if(el('edit-scene-profile').value!==library.clips.find(c=>c.id===editingScene.clip_id).profile)await call('setClipProfile',{id:editingScene.clip_id,value:el('edit-scene-profile').value});message('Scene details saved.');await reload();}));
 el('edit-scene-remove').addEventListener('click',()=>safe(async()=>{await call('remove',{id:editingScene.id});message('Scene removed. Undo is available in Library.');await reload();}));for(const action of ['undo','redo'])el('library-'+action).addEventListener('click',()=>safe(()=>undoRedo(action)));
 async function undoRedo(action){await window.LUTProduct.flush?.();const result=await call(action);library=result;message(action==='undo'?'Edit undone.':'Edit restored.');await reload(false);}
 document.addEventListener('keydown',event=>{if(!(event.metaKey||event.ctrlKey)||event.altKey||event.defaultPrevented||document.querySelector('dialog[open]')||event.target.closest('input,textarea,select,[contenteditable=true]'))return;const key=event.key.toLowerCase(),action=key==='z'?(event.shiftKey?'redo':'undo'):key==='y'&&!event.metaKey?'redo':null;if(action){event.preventDefault();safe(()=>undoRedo(action));}});
 el('edit-lut-save').addEventListener('click',()=>safe(async()=>{await call('updateLut',{id:editingLut.id,name:el('edit-lut-name').value,input:el('edit-lut-input').value,output:el('edit-lut-output').value,favourite:el('edit-lut-favourite').checked,code:el('edit-lut-code').value,maker:el('edit-lut-maker').value,description:el('edit-lut-description').value,tags:el('edit-lut-tags').value,expectedRevision:editingLut.aiRevision,aiSource:editingLut.aiSource});message('LUT details saved. Original contents unchanged.');await reload();}));
 window.LUTLibrary={call,reload,refresh,profiles,getState:()=>library,acceptSnapshot:value=>{library=value;draw();}};
 for(const kind of ['scene','lut'])el(`edit-${kind}-ai`).addEventListener('click',()=>window.LUTAI.open({kind,item:kind==='scene'?editingScene:editingLut,sceneId:window.LUTProduct.getSelection().scene}));
 el('library-ai').addEventListener('click',()=>window.LUTAI.settings());
 const size=bytes=>{if(bytes<1024)return bytes+' B';const units=['KB','MB','GB','TB'];let n=bytes/1024,i=0;while(n>=1024&&i<units.length-1){n/=1024;i++;}return n.toFixed(n<10?1:0)+' '+units[i];};
 let storageBusy=false;
 async function drawStorage(){const usage=await call('storageUsage'),labels={clips:'Imported clips',frames:'Saved scene frames',luts:'LUT files',gallery:'Saved viewer images',cache:'Generated previews',backups:'Backups',staging:'Temporary files',database:'Library records'};el('storage-usage').replaceChildren(...Object.entries(usage.categories).map(([key,value])=>{const row=node('div',undefined,'storage-row');row.append(node('span',labels[key]),node('span',size(value.bytes)));return row;}));el('storage-free').textContent=`${size(usage.totalBytes)} used · ${size(usage.freeBytes)} free on disk`;el('storage-clear').disabled=!usage.categories.cache.files;}
 el('library-storage').addEventListener('click',()=>safe(async()=>{el('storage-status').textContent='';await drawStorage();el('storage-dialog').showModal();}));
 el('storage-close').addEventListener('click',()=>{if(!storageBusy)el('storage-dialog').close();});el('storage-dialog').addEventListener('cancel',event=>{if(storageBusy)event.preventDefault();});
 el('storage-clear').addEventListener('click',async()=>{if(storageBusy)return;storageBusy=true;el('storage-clear').disabled=true;el('storage-close').disabled=true;el('storage-status').textContent='Clearing generated previews…';try{const removed=await call('clearCache');el('storage-status').textContent=`Cleared ${size(removed.bytes)}. Saved work is unchanged.`;await drawStorage();}catch(error){el('storage-status').textContent=error.message;el('storage-clear').disabled=false;}finally{storageBusy=false;el('storage-close').disabled=false;}});

 el('library-save-project').addEventListener('click',()=>safe(async()=>{await window.LUTProduct.flush?.();const result=await call('saveProject');const link=node('a');link.href=result.url;link.download=result.name+'.lutproject';document.body.append(link);link.click();link.remove();message(result.linkedCount?'Project saved with scenes, LUTs and adjustments. Linked originals stay separate; link them again to capture more frames after opening this project.':'Project saved with its footage, scenes, LUTs and adjustments.');}));
 el('library-open-project').addEventListener('click',()=>el('library-project-file').click());el('library-project-file').addEventListener('change',event=>safe(async()=>{const file=event.target.files[0];event.target.value='';if(!file)return;await window.LUTProduct.flush?.();uploadController=new AbortController();try{const response=await fetch('api/upload/project',{method:'POST',headers:{'X-LUT-Token':boot.token,'Content-Type':'application/octet-stream'},body:file,signal:uploadController.signal});const result=await response.json();if(!response.ok||!result.ok)throw Error(result.error);location.href=`index.html?project=${result.data.projectId}`;}finally{uploadController=undefined;}}));
 let backups=[];function backupProjects(){const backup=backups.find(b=>b.id===el('restore-backup').value);options(el('restore-project'),backup?.projects.map(p=>[p.id,p.name])||[]);}
 el('library-restore-backup').addEventListener('click',()=>safe(async()=>{backups=await call('listBackups');if(!backups.length){message('No library backups yet. Use Back up library first.');return;}options(el('restore-backup'),backups.map(b=>[b.id,new Date(b.date).toLocaleString()]));backupProjects();el('restore-status').textContent='';el('restore-dialog').showModal();}));el('restore-backup').addEventListener('change',backupProjects);el('restore-close').addEventListener('click',()=>el('restore-dialog').close());el('restore-open').addEventListener('click',async()=>{el('restore-open').disabled=true;el('restore-status').textContent='Opening a separate copy…';try{await window.LUTProduct.flush?.();const result=await call('restoreProject',{backupId:el('restore-backup').value,projectId:el('restore-project').value});location.href=`index.html?project=${result.projectId}`;}catch(error){el('restore-status').textContent=error.message;}finally{el('restore-open').disabled=false;}});
 el('library-backup').addEventListener('click',()=>safe(async()=>{const folder=await call('backup');message(`Library backup saved: ${folder}`);}));
 el('library-cancel').addEventListener('click',()=>{uploadController?.abort();safe(()=>call('cancel'));});
 const poll=async()=>{try{const response=await fetch('api/progress');const value=await response.json();el('library-progress').hidden=!value.text;el('library-progress-text').textContent=value.text;}catch{}finally{pollTimer=setTimeout(poll,500);}};poll();
 window.addEventListener('beforeunload',()=>clearTimeout(pollTimer));
 el('scene').addEventListener('change',()=>{if(library)drawScenes();});
 const reopen=sessionStorage.getItem('library-reopen');if(reopen){sessionStorage.removeItem('library-reopen');showTab(reopen);safe(open);}
})();

// Optional donations belong to the tool, not a user's saved project.
(()=>{
 const button=document.getElementById('coffee-open'),panel=document.getElementById('coffee-popover'),closeButton=document.getElementById('coffee-close'),link=document.getElementById('coffee-donate');
 try{const url=new URL(panel.dataset.donationUrl);if(url.protocol==='https:'&&!url.username&&!url.password){link.href=url.href;link.hidden=false;document.getElementById('coffee-coming-soon').hidden=true;}}catch{}
 function position(){if(panel.hidden)return;const anchor=button.getBoundingClientRect(),margin=12;panel.style.left=Math.max(margin,Math.min(anchor.right-panel.offsetWidth,window.innerWidth-panel.offsetWidth-margin))+'px';panel.style.top=Math.min(anchor.bottom+8,Math.max(margin,window.innerHeight-panel.offsetHeight-margin))+'px';}
 function close(restoreFocus=false){panel.hidden=true;button.setAttribute('aria-expanded','false');if(restoreFocus)button.focus({preventScroll:true});}
 button.addEventListener('click',()=>{if(!panel.hidden){close(true);return;}panel.hidden=false;button.setAttribute('aria-expanded','true');position();closeButton.focus({preventScroll:true});});
 closeButton.addEventListener('click',()=>close(true));
 document.addEventListener('pointerdown',event=>{if(!panel.hidden&&!panel.contains(event.target)&&!button.contains(event.target))close();});
 document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!panel.hidden){event.preventDefault();event.stopImmediatePropagation();close(true);}},true);
 panel.addEventListener('keydown',event=>event.stopPropagation());
 panel.addEventListener('focusout',()=>setTimeout(()=>{if(!panel.hidden&&!panel.contains(document.activeElement)&&document.activeElement!==button)close();},0));
 window.addEventListener('resize',position);window.addEventListener('scroll',position,true);
})();
